import { describe, it, expect, vi, beforeEach } from 'vitest';

/**
 * replyMode metadata scoping of the semantic cache (D-085).
 *
 * The filter must be STRICT BOTH-WAYS with 'sales' normalized to omitted:
 *  - legacy rows (no replyMode field) were all generated by sales prompts, so
 *    they keep serving sales requests;
 *  - info requests only match rows saved under 'info';
 *  - a sales request never matches an info row.
 * A lenient rule (like channel/replyStyle) would hand a cached sales reply that
 * literally asks for the customer's phone to an info-mode page.
 */
vi.mock('../../src/db', () => ({ db: { execute: vi.fn() } }));

import { db } from '../../src/db';
import { semanticCacheService } from '../../src/services/kb/semantic-cache';

const EMBEDDING = [0.1, 0.2, 0.3];

function rowWith(metadata: Record<string, unknown>) {
    return {
        id: 'row-1',
        reply_text: 'cached reply',
        intent: 'QUESTION',
        metadata,
        similarity: '0.97',
    };
}

function mockRows(rows: unknown[]) {
    vi.mocked(db.execute).mockResolvedValue(rows as never);
}

describe('semantic cache — replyMode scope (strict both-ways, sales ≡ omitted)', () => {
    beforeEach(() => {
        vi.clearAllMocks();
    });

    it('legacy row (no replyMode field) serves a sales request', async () => {
        mockRows([rowWith({})]);
        const hit = await semanticCacheService.check('page-1', EMBEDDING, 'QUESTION', 3, { replyMode: 'sales' });
        expect(hit?.reply).toBe('cached reply');
    });

    it('legacy row (no replyMode field) serves a request with no mode at all', async () => {
        mockRows([rowWith({})]);
        const hit = await semanticCacheService.check('page-1', EMBEDDING, 'QUESTION', 3, {});
        expect(hit?.reply).toBe('cached reply');
    });

    it('legacy row is REJECTED for an info request (never serve a sales reply to an info page)', async () => {
        mockRows([rowWith({})]);
        const hit = await semanticCacheService.check('page-1', EMBEDDING, 'QUESTION', 3, { replyMode: 'info' });
        expect(hit).toBeNull();
    });

    it('info row is REJECTED for a sales request (the reverse leak)', async () => {
        mockRows([rowWith({ replyMode: 'info' })]);
        const hit = await semanticCacheService.check('page-1', EMBEDDING, 'QUESTION', 3, { replyMode: 'sales' });
        expect(hit).toBeNull();
    });

    it('info row serves an info request', async () => {
        mockRows([rowWith({ replyMode: 'info' })]);
        const hit = await semanticCacheService.check('page-1', EMBEDDING, 'QUESTION', 3, { replyMode: 'info' });
        expect(hit?.reply).toBe('cached reply');
    });

    it('save() omits the field for sales and stores it for info (keeps new sales rows legacy-shaped)', async () => {
        vi.mocked(db.execute).mockResolvedValue([] as never);

        await semanticCacheService.save({
            pageId: 'page-1', queryText: 'q', queryEmbedding: EMBEDDING, intent: 'QUESTION',
            replyText: 'r', kbActiveVersion: 3, replyMode: 'sales',
        });
        await semanticCacheService.save({
            pageId: 'page-1', queryText: 'q', queryEmbedding: EMBEDDING, intent: 'QUESTION',
            replyText: 'r', kbActiveVersion: 3, replyMode: 'info',
        });

        // The metadata object is interpolated into the sql template as a param —
        // inspect the queryChunks' bound params for the replyMode marker.
        const calls = vi.mocked(db.execute).mock.calls;
        const paramsOf = (call: unknown[]) => JSON.stringify((call[0] as { queryChunks?: unknown }).queryChunks ?? call[0]);
        expect(paramsOf(calls[0])).not.toContain('replyMode');
        expect(paramsOf(calls[1])).toContain('replyMode');
    });
});
