import { useCallback, useEffect, useRef, useState } from 'react';
import { useTranslations } from 'next-intl';
import { X, Copy, Check, Download, RefreshCw, Sparkles } from 'lucide-react';
import clsx from 'clsx';
import { toast } from 'sonner';
import type { PostSuggestionDto, PostSuggestionImageDegraded, PostSuggestionPostType } from '@jawab24/shared';
import { DetailSheet, Button } from '@/components/ui';
import { postSuggestionsApi, type PostSuggestionResponse } from '@/lib/api';
import { useCopyToClipboard } from '@/hooks';
import { downloadImage } from '@/utils/imageDownload';
import { captureError } from '@/lib/sentryHelpers';

/**
 * «بوست اليوم» viewer — today's suggested post: text to copy, image to
 * save/share, capped regenerate. No publishing: the merchant reviews and
 * posts manually (the review line is deliberate — industry norm is
 * AI-drafted, human-approved).
 *
 * Opened with `initial` when the dashboard already fetched today's
 * suggestion; opened with null it generates immediately (the card's CTA
 * path). Every user signal (open/copy/download) is stamped fire-and-forget —
 * those stamps ARE the pilot's success metric.
 */
export function PostSuggestionSheet({
  pageId,
  initial,
  canGenerate,
  onClose,
  onChanged,
}: {
  pageId: string;
  initial: PostSuggestionResponse | null;
  /** Workspace admins only — the generate route is requireRole('admin'). */
  canGenerate: boolean;
  onClose: () => void;
  /** Bubble the latest server state up so the card stays in sync. */
  onChanged: (latest: PostSuggestionResponse) => void;
}) {
  const t = useTranslations('postSuggestions');
  const tc = useTranslations('common');
  const { copied, copy } = useCopyToClipboard();

  const [suggestion, setSuggestion] = useState<PostSuggestionDto | null>(initial?.suggestion ?? null);
  // null = UNKNOWN (cap store degraded server-side) — never treated as 0:
  // regenerate stays enabled and the generate route fails closed on its own.
  const [remaining, setRemaining] = useState<number | null>(initial?.remainingToday ?? null);
  // Why the current suggestion is text-only (visibility: the notice itself is
  // derived from the DATA — suggestion without imageUrl — not from this flag).
  const [degradedReason, setDegradedReason] = useState<PostSuggestionImageDegraded | undefined>(initial?.imageDegraded);
  // Angles this page's data can deliver. null = UNKNOWN ⇒ chips FAIL CLOSED
  // (only 'general' enabled) — never offer an angle that may burn one of the
  // capped attempts on nothing. Updated from every response that carries it.
  const [availableTypes, setAvailableTypes] = useState<PostSuggestionPostType[] | null>(initial?.availableTypes ?? null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // Merchant choice: append the verified contact footer (address/phone/WhatsApp)?
  // Default ON; applies to the NEXT generation (the server composes the footer).
  const [includeContact, setIncludeContact] = useState(true);
  // Which take is on screen. Seeded from the server so reopening the sheet
  // shows the one the merchant last chose, not take 1 again.
  const [variantIndex, setVariantIndex] = useState(initial?.suggestion?.selectedVariant ?? 0);
  // Merchant's local edits, PER TAKE — switching away and back must not throw
  // away what they typed. Keyed by index, reset per suggestion.
  const [editsByVariant, setEditsByVariant] = useState<Record<number, string>>({});
  // Which angle the merchant just asked for — echoed in the loading state so a
  // ~30s generation never feels like a dead click (dogfood feedback 08-09).
  const [pendingType, setPendingType] = useState<PostSuggestionPostType | null>(null);
  const stampedOpen = useRef(false);
  // Auto-generate must fire ONCE per sheet open: StrictMode double-mounts
  // effects in dev, and each paid call consumes a daily-cap slot — caught
  // live (two POSTs in the same millisecond) during the local pilot run.
  const autoGenerated = useRef(false);

  const stamp = useCallback((id: string, event: 'opened' | 'copied' | 'downloaded') => {
    postSuggestionsApi.markEvent(pageId, id, event).catch((err) => {
      // Signal only — never user-visible. A 5xx is real contract breakage on
      // the pilot's metric route and must reach Sentry; network blips and 404s
      // (dark feature / deleted row) stay swallowed to avoid mobile noise.
      const status = (err as { response?: { status?: number } }).response?.status;
      if (typeof status === 'number' && status >= 500) {
        captureError(err, 'Post suggestion event stamp failed', { extra: { pageId, event } });
      }
    });
  }, [pageId]);

  const generate = useCallback(async (postType?: PostSuggestionPostType) => {
    setPendingType(postType ?? null);
    setLoading(true);
    setError(null);
    // Remembered for the recovery below: the post that was on screen BEFORE
    // this generation, so a recovered row can be told apart from it.
    const priorId = suggestion?.id ?? null;
    try {
      const res = await postSuggestionsApi.generate(pageId, includeContact, postType);
      setSuggestion(res.data.suggestion);
      setRemaining(res.data.remainingToday);
      setDegradedReason(res.data.imageDegraded);
      if (res.data.availableTypes) setAvailableTypes(res.data.availableTypes);
      onChanged(res.data);
    } catch (err) {
      const axiosErr = err as { response?: { status?: number; data?: { code?: string } } };
      const code = axiosErr.response?.data?.code;
      if (code === 'daily_cap') setError(t('errorDailyCap'));
      else if (code === 'quota_check_unavailable') setError(t('errorQuotaCheck'));
      else if (code === 'generation_failed') setError(t('errorGeneration'));
      // Route-level limiter (2/min) — expected throttling under normal
      // clicking, distinct from the daily cap; never a Sentry event (the
      // server already fingerprints it on its side).
      else if (code === 'RATE_LIMIT_EXCEEDED') setError(t('errorRateLimit'));
      else if (!axiosErr.response) {
        // NO HTTP RESPONSE — the connection died, which says nothing about
        // whether the server finished. It usually DID: generation runs ~35s
        // against nginx's 30s proxy_read_timeout on this route, so the socket
        // closes while the work completes and commits. Reported live
        // 2026-08-12: the merchant saw «حدث خطأ ما» while their post existed,
        // with a capped attempt already spent on it.
        //
        // So ask before despairing. A row whose id differs from what was on
        // screen is THIS generation's result — adopt it and there is no error
        // to report. Same id (or none) means nothing landed, and the generic
        // error is then the honest answer.
        try {
          const latest = await postSuggestionsApi.getToday(pageId);
          const recovered = latest.data.suggestion;
          if (recovered && recovered.id !== priorId) {
            setSuggestion(recovered);
            setRemaining(latest.data.remainingToday);
            setDegradedReason(latest.data.imageDegraded);
            if (latest.data.availableTypes) setAvailableTypes(latest.data.availableTypes);
            onChanged(latest.data);
            return;
          }
        } catch {
          // Recovery is best-effort; fall through to the error below.
        }
        setError(t('errorGeneric'));
        captureError(err, 'Post suggestion generation failed', { extra: { pageId, recovered: false } });
      } else {
        setError(t('errorGeneric'));
        captureError(err, 'Post suggestion generation failed', { extra: { pageId } });
      }
    } finally {
      setLoading(false);
    }
  }, [pageId, onChanged, t, includeContact, suggestion]);

  // The take on screen, and the text the merchant sees for it (their edit if
  // they made one, the model's otherwise). One derivation — every consumer
  // (textarea, copy, the switcher) reads THESE, so they cannot disagree.
  //
  // The empty-`variants` fallback is not defensive padding: during a blue/green
  // deploy this bundle can be served a response from the OLD backend, which has
  // no `variants` field at all. Projecting the columns it DOES send keeps the
  // sheet fully usable in that window instead of showing an empty textarea.
  const variants = suggestion
    ? (suggestion.variants?.length
      ? suggestion.variants
      : [{ text: suggestion.text, headline: null, imageUrl: suggestion.imageUrl }])
    : [];
  const activeIndex = variantIndex < variants.length ? variantIndex : 0;
  const activeVariant = variants[activeIndex];
  const activeText = editsByVariant[activeIndex] ?? activeVariant?.text ?? '';
  const activeImageUrl = activeVariant?.imageUrl ?? null;

  // Opened with a suggestion → stamp `opened` once. Opened empty (CTA path) →
  // generate immediately, if this member is allowed to.
  //
  // Keyed on the suggestion's ID, NOT the object. Saving a take swaps in a
  // fresh object with the same id, and resetting on that would delete whatever
  // the merchant had typed the instant their choice finished saving — losing
  // typed work is the exact failure this whole feature exists to end. A
  // REGENERATE mints a new id, which is the case that genuinely must reset.
  const suggestionId = suggestion?.id ?? null;
  useEffect(() => {
    setEditsByVariant({});
    setVariantIndex(suggestion?.selectedVariant ?? 0);
    if (suggestion && !stampedOpen.current) {
      stampedOpen.current = true;
      stamp(suggestion.id, 'opened');
    } else if (!suggestion && !loading && !error && canGenerate && !autoGenerated.current) {
      autoGenerated.current = true;
      void generate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps -- mount + new-suggestion only
  }, [suggestionId]);

  // Unknown remaining (null) keeps regenerate ENABLED — only a confirmed 0
  // disables it; the generate route fails closed server-side regardless.
  const canRegenerate = canGenerate && remaining !== 0;

  /**
   * Switch takes. The choice is persisted so every OTHER reader agrees with
   * what the merchant is looking at — the dashboard card, and app bundles that
   * predate variants and can only read the mirrored columns.
   *
   * Optimistic: the switch is local state and paints immediately; the PUT
   * follows. A failed PUT is not surfaced — the merchant can still read, edit,
   * copy and download the take they picked, so an error toast would report a
   * problem they do not have. It reaches Sentry instead.
   */
  const selectVariant = (index: number) => {
    setVariantIndex(index);
    if (!suggestion || index === suggestion.selectedVariant) return;
    postSuggestionsApi.selectVariant(pageId, suggestion.id, index)
      .then((res) => setSuggestion(res.data.suggestion))
      .catch((err) => captureError(err, 'Post suggestion variant selection failed', { extra: { pageId, index } }));
  };

  const handleCopy = async () => {
    if (!suggestion) return;
    // The `copied` stamp IS the pilot's success metric — stamp only when the
    // clipboard write actually landed, never on a blocked/absent API.
    const ok = await copy(activeText);
    if (ok) stamp(suggestion.id, 'copied');
    else toast.error(t('copyFailed'));
  };

  const handleDownload = async () => {
    if (!activeImageUrl || !suggestion) return;
    try {
      const { savedToFiles } = await downloadImage(activeImageUrl, `jawab24-post-${suggestion.suggestedFor}.jpg`);
      stamp(suggestion.id, 'downloaded');
      toast.success(savedToFiles ? t('imageSavedToFiles') : t('imageDownloadStarted'));
    } catch (err) {
      captureError(err, 'Post suggestion image download failed', { extra: { pageId } });
      toast.error(t('errorGeneric'));
    }
  };

  return (
    <DetailSheet
      fitContent
      onSwipeDismiss={onClose}
      panelClassName="sm:max-w-lg"
      dialogProps={{ role: 'dialog', 'aria-modal': true, 'aria-labelledby': 'post-suggestion-title' }}
    >
      {/* Header */}
      <div className="flex items-center justify-between gap-3 px-4 py-3 sm:p-5 border-b border-theme-border flex-shrink-0">
        <h2 id="post-suggestion-title" className="text-base sm:text-lg font-semibold text-foreground flex items-center gap-2">
          <Sparkles className="w-5 h-5 text-brand-500" aria-hidden="true" />
          {t('sheetTitle')}
        </h2>
        <button
          type="button"
          onClick={onClose}
          aria-label={tc('close')}
          // hover:bg-surface-100 was invisible in dark mode — that token is
          // synced to --card, so the hover state painted the card's own colour.
          className="min-h-[44px] min-w-[44px] -me-2 flex items-center justify-center rounded-lg hover:bg-surface-200 dark:hover:bg-surface-300 text-icon-muted"
        >
          <X className="w-5 h-5" aria-hidden="true" />
        </button>
      </div>

      {/* Body */}
      <div className="flex-1 min-h-0 overflow-y-auto overscroll-contain p-4 sm:p-5 space-y-4">
        {loading && (
          <div className="py-10 text-center space-y-2" aria-busy="true" aria-live="polite">
            <RefreshCw className="w-6 h-6 mx-auto animate-spin text-brand-500" aria-hidden="true" />
            <p className="text-sm font-semibold text-foreground">
              {pendingType ? t('generatingAngle', { angle: t(`type_${pendingType}`) }) : t('generating')}
            </p>
            <p className="text-xs text-muted-foreground">{t('generatingHint')}</p>
          </div>
        )}

        {!loading && error && (
          <div className="alert-error rounded-xl p-4 text-sm" role="alert">{error}</div>
        )}

        {!loading && suggestion && (
          <>
            {/* Take switcher — the generation's takes, side by side. Hidden for
                a single-take suggestion (every row generated before variants
                shipped), so nothing changes for those. */}
            {variants.length > 1 && (
              // Deliberately the same filled-pill shape as the angle chips and
              // the card's page switcher rather than a tinted-track segmented
              // control: `surface-100` is synced to `--card` in dark mode, so a
              // track drawn with it disappears and takes the active pill's
              // contrast with it. Brand fill reads in both themes.
              <div role="tablist" aria-label={t('variantsLabel')} className="flex gap-1.5">
                {variants.map((_, index) => (
                  <button
                    key={index}
                    type="button"
                    role="tab"
                    aria-selected={index === activeIndex}
                    onClick={() => selectVariant(index)}
                    className={clsx(
                      'flex-1 min-h-[44px] rounded-xl px-2 text-xs font-semibold border transition-colors',
                      index === activeIndex
                        ? 'bg-brand-500 text-white border-brand-500'
                        : 'bg-card text-muted-foreground border-theme-border hover:border-brand-300',
                    )}
                  >
                    {t('variantTab', { number: index + 1 })}
                  </button>
                ))}
              </div>
            )}

            {activeImageUrl ? (

              // generated media; not a build-time asset and the host is outside
              // next.config remotePatterns, so next/image cannot serve it.
              <img
                key={activeImageUrl}
                src={activeImageUrl}
                alt={t('postImageAlt')}
                // The cards are square 1024×1024. At `w-full` that is a
                // full-viewport-width square, which pushed Copy/Download below
                // the fold on a long post — and in LANDSCAPE made the image
                // alone taller than the whole sheet (panel ≈378px, image
                // ≈472px), so the merchant landed on a picture with every
                // action off-screen. Bound it by HEIGHT and let width follow.
                // The intrinsic size attributes reserve the box, so neither the
                // first load nor switching takes shifts the layout under a
                // thumb already reaching for a button.
                width={1024}
                height={1024}
                className="mx-auto h-auto w-auto max-h-[38vh] landscape:max-h-[30vh] rounded-xl border border-theme-border"
              />
            ) : (
              // Derived from the DATA (no imageUrl = text-only), not from the
              // transport-state degrade flag — a cron text-only row arriving
              // via getToday gets the same explanation as a fresh degrade.
              <p className="text-xs text-muted-foreground">
                {degradedReason === 'storage_off' ? t('textOnlyStorageOff') : t('textOnlyNotice')}
              </p>
            )}

            {/* Editable copy — the merchant tweaks freely; Copy copies THEIR version. */}
            <textarea
              dir="auto"
              value={activeText}
              onChange={(e) => setEditsByVariant((prev) => ({ ...prev, [activeIndex]: e.target.value }))}
              aria-label={t('editTextLabel')}
              rows={Math.min(10, Math.max(4, activeText.split('\n').length + 1))}
              className="w-full rounded-xl border border-theme-border bg-background p-3 text-sm text-foreground text-start leading-relaxed resize-y focus:outline-none focus:ring-2 focus:ring-brand-300"
            />

            <p className="text-xs text-muted-foreground">{t('reviewBeforePosting')}</p>

            {canRegenerate && (
              <>
                {/* Angle chooser — regenerate with a specific type (consumes a slot).
                    An angle the page's DATA can't deliver is disabled, never hidden:
                    the merchant sees what exists and what filling their Business
                    Info would unlock (complete-your-profile pattern). */}
                <div>
                  <p className="text-xs font-medium text-muted-foreground mb-1.5">{t('tryAngle')}</p>
                  <div className="flex flex-wrap gap-1.5">
                    {(['promo', 'product_spotlight', 'faq_tip', 'hours_reminder', 'general'] as const).map((type) => {
                      // FAIL CLOSED: unknown availability offers only 'general'
                      // — a chip must never burn a capped attempt on an angle
                      // the page's data can't deliver (dogfood 08-09).
                      const enabled = availableTypes ? availableTypes.includes(type) : type === 'general';
                      return (
                        <button
                          key={type}
                          type="button"
                          disabled={!enabled}
                          title={enabled ? undefined : t('angleNeedsData')}
                          onClick={() => void generate(type)}
                          className={clsx(
                            // 44px: these were ~28px tall, against a close
                            // button in the same header that already pins 44.
                            'min-h-[44px] px-4 rounded-full text-xs font-medium border transition-colors',
                            !enabled && 'opacity-40 cursor-not-allowed',
                            suggestion.postType === type
                              ? 'bg-brand-500 text-white border-brand-500'
                              : 'bg-card text-muted-foreground border-theme-border hover:border-brand-300',
                          )}
                        >
                          {t(`type_${type}`)}
                        </button>
                      );
                    })}
                  </div>
                  {(!availableTypes || availableTypes.length < 5) && (
                    <p className="text-[11px] text-subtle mt-1.5">{t('angleNeedsDataHint')}</p>
                  )}
                </div>

                <label className="flex items-center gap-2 text-xs text-muted-foreground cursor-pointer select-none">
                  <input
                    type="checkbox"
                    checked={includeContact}
                    onChange={(e) => setIncludeContact(e.target.checked)}
                    className="rounded border-theme-border accent-brand-500"
                  />
                  {t('includeContactToggle')}
                </label>
              </>
            )}

            {/* null = unknown — assert neither a count nor "exhausted". */}
            {remaining !== null && (
              <p className="text-xs text-subtle">
                {remaining > 0 ? t('remaining', { count: remaining }) : t('noRemaining')}
              </p>
            )}
          </>
        )}
      </div>

      {/* Fixed footer (Rule 3: scrollable body, fixed header/footer). Copy is
          the action this whole feature exists to produce — 16 posts generated
          in the pilot and not one ever copied — so it must never be the thing
          the merchant has to scroll past an image and an editor to reach.
          pb-safe-modal clears the home indicator; it collapses on its own when
          the keyboard is open, so the bar rides above it while editing. */}
      {!loading && suggestion && (
        <div className="flex-shrink-0 border-t border-theme-border bg-card px-4 py-3 sm:px-5 pb-safe-modal flex flex-wrap gap-2">
          <Button variant="secondary" size="sm" className="min-h-[44px] flex-1 sm:flex-none" onClick={() => void handleCopy()}>
            {copied ? <Check className="w-4 h-4 me-1.5" aria-hidden="true" /> : <Copy className="w-4 h-4 me-1.5" aria-hidden="true" />}
            {copied ? t('copied') : t('copyText')}
          </Button>
          {activeImageUrl && (
            <Button variant="secondary" size="sm" className="min-h-[44px] flex-1 sm:flex-none" onClick={handleDownload}>
              <Download className="w-4 h-4 me-1.5" aria-hidden="true" />
              {t('downloadImage')}
            </Button>
          )}
          {canRegenerate && (
            <Button variant="ghost" size="sm" className="min-h-[44px]" onClick={() => void generate()}>
              <RefreshCw className="w-4 h-4 me-1.5" aria-hidden="true" />
              {t('regenerate')}
            </Button>
          )}
        </div>
      )}
    </DetailSheet>
  );
}
