-- Add missing columns to settings table
ALTER TABLE settings ADD COLUMN IF NOT EXISTS comments_auto_reply BOOLEAN DEFAULT TRUE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS messages_auto_reply BOOLEAN DEFAULT TRUE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS comment_reply_mode VARCHAR(20) DEFAULT 'public';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS dual_reply_config JSONB DEFAULT '{}';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS business_hours_only BOOLEAN DEFAULT FALSE;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS business_hours_start VARCHAR(5) DEFAULT '09:00';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS business_hours_end VARCHAR(5) DEFAULT '18:00';
ALTER TABLE settings ADD COLUMN IF NOT EXISTS away_message TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS greeting_message TEXT;
ALTER TABLE settings ADD COLUMN IF NOT EXISTS reply_delay INTEGER DEFAULT 0;
