-- Retire the SMS delivery rail: WhatsApp is the only customer-notification
-- channel (D-123 — the Vonage provider was dropped by owner ruling 2026-08-25).
--
-- The `ALTER ... SET DEFAULT` line is drizzle-generated (it is the DDL `schema.ts`
-- declares, so it MUST come from `drizzle-kit generate` and carry its snapshot —
-- a hand-written equivalent leaves `meta/0186_snapshot.json` absent, the next
-- `generate` re-emits the same statement, and `scripts/check-schema-drift.sh`
-- fails the deploy). The backfills below are hand-added on top; they touch data
-- only, so they do not belong in the snapshot.
--
-- Measured before writing (production, read-only, 2026-09-03): 12 template rows,
-- every one channel='sms' AND is_enabled=false, and customer_notifications_log
-- is empty. So the backfill changes no observable behaviour today — it removes a
-- dead default before a merchant can switch a type on and hit it.
ALTER TABLE "customer_notification_templates" ALTER COLUMN "channel" SET DEFAULT 'whatsapp';--> statement-breakpoint
-- The rows that already exist all carry 'sms' and would otherwise route to a
-- rail whose code is gone.
--
-- Deliberately does NOT touch `updated_at`: it is the only proxy for when a
-- merchant last edited a template, and stamping 12 rows would destroy it
-- (AI_INSTRUCTIONS Rule 10.11c). Verified 2026-09-03 that the table carries no
-- trigger that would stamp it behind this statement's back.
UPDATE "customer_notification_templates" SET "channel" = 'whatsapp' WHERE "channel" = 'sms';--> statement-breakpoint
-- Queued log rows too. Empty in production today (0 rows), but a merchant who
-- switches a type on between this measurement and the deploy would enqueue a row
-- stamped with the template's still-'sms' channel, and `send()` now fails such a
-- row permanently with `channel_unsupported`. Scoped to rows that have not been
-- acted on: a historical 'sms' row's channel is a FACT about how it was sent
-- (or failed), and the analytics funnel groups by it — rewriting those would be
-- falsifying the record.
UPDATE "customer_notifications_log" SET "channel" = 'whatsapp' WHERE "channel" = 'sms' AND "status" = 'pending';
