import { db } from '../db';
import { deviceTokens, notifications, settings } from '../db/schema';
import { eq, and, desc, count } from 'drizzle-orm';
import { captureError } from '../utils/sentryHelpers';
import { flagReasonEn, flagReasonAr } from '@jawab24/shared';

// Notification types
export type NotificationType =
    | 'payment_failed'
    | 'subscription_expiring'
    | 'page_disconnected'
    | 'subscription_renewed'
    | 'trial_ending'
    | 'flagged_reply'
    | 'skipped_reply'
    | 'new_comment'
    | 'stale_comment'
    | 'stale_message'
    | 'kb_gap'
    | 'provider_failover';

export interface NotificationPayload {
    type: NotificationType;
    titles: Record<string, string>;  // { en: '...', ar: '...', fr: '...' }
    bodies: Record<string, string>;  // { en: '...', ar: '...', fr: '...' }
    data?: Record<string, unknown>;
}

/** Default fallback language when the requested locale has no translation */
const FALLBACK_LANG = 'en';

// Notification templates — keyed by locale for easy multi-language expansion
export const NOTIFICATION_TEMPLATES: Record<NotificationType, Pick<NotificationPayload, 'titles' | 'bodies'>> = {
    payment_failed: {
        titles: { en: 'Payment Failed', ar: 'فشل الدفع' },
        bodies: {
            en: 'We couldn\'t process your payment. Please update your payment method to continue using Jawab24.',
            ar: 'لم نتمكن من معالجة الدفع. يرجى تحديث طريقة الدفع لمواصلة استخدام Jawab24.',
        },
    },
    subscription_expiring: {
        titles: { en: 'Subscription Expiring Soon', ar: 'اشتراكك ينتهي قريباً' },
        bodies: {
            en: 'Your subscription expires in {days} days. Renew now to avoid service interruption.',
            ar: 'ينتهي اشتراكك خلال {days} أيام. جدد الآن لتجنب انقطاع الخدمة.',
        },
    },
    page_disconnected: {
        titles: { en: 'Page Disconnected', ar: 'تم فصل الصفحة' },
        bodies: {
            en: 'Your page \'{pageName}\' has been disconnected. Please reconnect to resume auto-replies.',
            ar: 'تم فصل صفحتك \'{pageName}\'. يرجى إعادة الاتصال لاستئناف الرد التلقائي.',
        },
    },
    subscription_renewed: {
        titles: { en: 'Subscription Renewed', ar: 'تم تجديد الاشتراك' },
        bodies: {
            en: 'Your subscription has been successfully renewed. Thank you for using Jawab24!',
            ar: 'تم تجديد اشتراكك بنجاح. شكراً لاستخدامك Jawab24!',
        },
    },
    trial_ending: {
        titles: { en: 'Trial Ending Soon', ar: 'تنتهي الفترة التجريبية قريباً' },
        bodies: {
            en: 'Your free trial ends in {days} days. Subscribe now to keep using Jawab24.',
            ar: 'تنتهي فترتك التجريبية المجانية خلال {days} أيام. اشترك الآن للاستمرار في استخدام Jawab24.',
        },
    },
    flagged_reply: {
        titles: { en: 'Reply Needs Your Attention', ar: 'رد يحتاج انتباهك' },
        bodies: {
            en: 'A Smart Reply to "{senderName}" was flagged: {reason}. Please review it.',
            ar: 'تم وضع علامة على رد ذكي لـ "{senderName}": {reason}. يرجى مراجعته.',
        },
    },
    skipped_reply: {
        titles: { en: 'Auto-Reply Skipped', ar: 'تم تخطي الرد التلقائي' },
        bodies: {
            en: 'A reply to "{senderName}" was skipped: {reason}. Please review and reply manually.',
            ar: 'تم تخطي الرد التلقائي لـ "{senderName}": {reason}. يرجى مراجعته والرد يدوياً.',
        },
    },
    new_comment: {
        titles: { en: 'New Comment', ar: 'تعليق جديد' },
        bodies: {
            en: 'New comment from {senderName} is waiting for your reply.',
            ar: 'تعليق جديد من {senderName} بانتظار ردك.',
        },
    },
    stale_comment: {
        titles: { en: '{senderName} — {pageName}', ar: '{senderName} — {pageName}' },
        bodies: { en: '{preview}', ar: '{preview}' },
    },
    stale_message: {
        titles: { en: '{senderName} — {pageName}', ar: '{senderName} — {pageName}' },
        bodies: { en: '{preview}', ar: '{preview}' },
    },
    kb_gap: {
        titles: { en: 'Knowledge Base Gap Detected', ar: 'فجوة في قاعدة المعرفة' },
        bodies: {
            en: 'Customers on "{pageName}" keep asking about "{topic}" but your knowledge base doesn\'t cover it.',
            ar: 'عملاء "{pageName}" يسألون عن "{topic}" لكن قاعدة المعرفة لا تغطي هذا الموضوع.',
        },
    },
    provider_failover: {
        titles: { en: 'AI Provider Failover Active', ar: 'تم تفعيل مزود الذكاء الاصطناعي الاحتياطي' },
        bodies: {
            en: 'OpenAI is unreachable. Replies are being generated by {fallbackModel}. Check your OpenAI account status.',
            ar: 'لا يمكن الوصول إلى OpenAI. يتم إنشاء الردود بواسطة {fallbackModel}. تحقق من حالة حساب OpenAI الخاص بك.',
        },
    },
};

/** Internal-only flag fragments that carry metadata, not user-facing reasons.
 *  These are stripped before the reason string is shown to the user. */
const METADATA_FLAG_PREFIXES = ['expected_lang:', 'reply_lang:'];

// Single source of truth: packages/shared/src/i18n/{en,ar}/flagReason.json
const FLAG_REASON_EN: Record<string, string> = flagReasonEn;
const FLAG_REASON_AR: Record<string, string> = flagReasonAr;

/** Arabic fallback for 'Unknown' sender name */
const UNKNOWN_SENDER_AR = 'مجهول';

function translateFlagReason(reason: string, lang: string): string {
    const map = lang === 'ar' ? FLAG_REASON_AR : FLAG_REASON_EN;
    const separator = lang === 'ar' ? '، ' : ', ';

    // Exact match (simple flags like "angry_customer")
    if (map[reason]) return map[reason];

    // Enriched reasons like "Cancellation Request — order #5678":
    // translate the label prefix and keep the suffix (order number).
    for (const [key, val] of Object.entries(map)) {
        if (reason.startsWith(key) && reason.length > key.length && reason[key.length] === ' ') {
            return val + reason.slice(key.length);
        }
    }

    // Comma-separated flags (e.g., "language_mismatch,expected_lang:en,reply_lang:ar")
    // Strip internal metadata flags (expected_lang:*, reply_lang:*) before translating.
    const parts = reason.split(',')
        .map(f => f.trim())
        .filter(f => !METADATA_FLAG_PREFIXES.some(prefix => f.startsWith(prefix)));

    return parts.map(f => map[f] || f).join(separator);
}

/**
 * Replace template placeholders in a localized string map.
 * Arabic gets special handling for `reason` (translated) and `senderName` ('Unknown' → مجهول).
 */
function replaceVariables(
    templateMap: Record<string, string>,
    variables: Record<string, string>,
): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [lang, text] of Object.entries(templateMap)) {
        let resolved = text;
        for (const [key, value] of Object.entries(variables)) {
            const placeholder = `{${key}}`;
            let replacement = value;
            if (key === 'reason') {
                replacement = translateFlagReason(value, lang);
            } else if (lang === 'ar' && key === 'senderName' && value === 'Unknown') {
                replacement = UNKNOWN_SENDER_AR;
            }
            resolved = resolved.replace(placeholder, replacement);
        }
        result[lang] = resolved;
    }
    return result;
}

class NotificationService {
    /**
     * Register a device token for push notifications
     */
    async registerDeviceToken(
        userId: string,
        token: string,
        platform: 'android' | 'ios' | 'web'
    ): Promise<void> {
        // Check if token already exists for this user
        const existing = await db
            .select()
            .from(deviceTokens)
            .where(and(
                eq(deviceTokens.userId, userId),
                eq(deviceTokens.token, token)
            ))
            .limit(1);

        if (existing.length > 0) {
            // Update last used timestamp
            await db
                .update(deviceTokens)
                .set({ lastUsedAt: new Date() })
                .where(eq(deviceTokens.id, existing[0].id));
        } else {
            try {
                await db.insert(deviceTokens).values({
                    userId,
                    token,
                    platform,
                });
            } catch (err: unknown) {
                // FK violation = user was deleted but JWT is still valid — ignore silently
                const pgErr = err as { code?: string };
                if (pgErr.code === '23503') return;
                throw err;
            }
        }
    }

    /**
     * Remove a device token (e.g., on logout)
     */
    async removeDeviceToken(userId: string, token: string): Promise<void> {
        await db
            .delete(deviceTokens)
            .where(and(
                eq(deviceTokens.userId, userId),
                eq(deviceTokens.token, token)
            ));
    }

    /**
     * Get all device tokens for a user
     */
    async getUserDeviceTokens(userId: string): Promise<string[]> {
        const tokens = await db
            .select({ token: deviceTokens.token })
            .from(deviceTokens)
            .where(eq(deviceTokens.userId, userId));

        return tokens.map(t => t.token);
    }

    /**
     * Create and send a notification to a user.
     * Stores all locale variants in JSONB; push uses user's preferred language.
     */
    async sendNotification(
        userId: string,
        payload: NotificationPayload
    ): Promise<string> {
        // 1. Store notification in database (for in-app display)
        const [notification] = await db
            .insert(notifications)
            .values({
                userId,
                type: payload.type,
                titles: payload.titles,
                bodies: payload.bodies,
                data: payload.data || {},
            })
            .returning({ id: notifications.id });

        // 2. Get user's device tokens and language preference
        const [tokens, userLanguage] = await Promise.all([
            this.getUserDeviceTokens(userId),
            this.getUserLanguage(userId),
        ]);

        // 3. Send push notification via FCM (if tokens exist and FCM is configured)
        if (tokens.length > 0) {
            await this.sendPushNotification(tokens, payload, userLanguage);
        }

        return notification.id;
    }

    /**
     * Send notification using a template.
     * Replaces {variables} in all locale variants, then delegates to sendNotification.
     */
    async sendTemplateNotification(
        userId: string,
        type: NotificationType,
        variables: Record<string, string> = {},
        data?: Record<string, unknown>
    ): Promise<string> {
        const template = NOTIFICATION_TEMPLATES[type];

        return this.sendNotification(userId, {
            type,
            titles: replaceVariables(template.titles, variables),
            bodies: replaceVariables(template.bodies, variables),
            data,
        });
    }

    /**
     * Get user's preferred language from settings
     */
    private async getUserLanguage(userId: string): Promise<string> {
        try {
            const [userSettings] = await db
                .select({ dashboardLanguage: settings.dashboardLanguage })
                .from(settings)
                .where(eq(settings.userId, userId))
                .limit(1);

            return userSettings?.dashboardLanguage || 'ar';
        } catch {
            return 'ar'; // Default to Arabic
        }
    }

    /**
     * Send push notification via FCM.
     * Uses user's preferred language for the notification display,
     * with fallback to English if the locale isn't available.
     */
    private async sendPushNotification(
        tokens: string[],
        payload: NotificationPayload,
        userLanguage: string = 'ar'
    ): Promise<void> {
        // Check if Firebase Admin is configured
        const firebaseCredentials = process.env.FIREBASE_SERVICE_ACCOUNT_KEY;

        if (!firebaseCredentials) {
            console.warn('[Notifications] FCM not configured, skipping push notification');
            return;
        }

        try {
            // Dynamic import to avoid errors when firebase-admin isn't installed
            // eslint-disable-next-line @typescript-eslint/no-require-imports
            const admin = require('firebase-admin');

            // Initialize Firebase Admin if not already initialized
            if (!admin.apps.length) {
                const serviceAccount = JSON.parse(firebaseCredentials);
                admin.initializeApp({
                    credential: admin.credential.cert(serviceAccount),
                });
            }

            // Resolve title/body for user's preferred language, with English fallback
            const title = payload.titles[userLanguage] || payload.titles[FALLBACK_LANG] || '';
            const body = payload.bodies[userLanguage] || payload.bodies[FALLBACK_LANG] || '';

            // Send all locale variants so the client can switch language without re-fetching
            const isUrgent = payload.data?.urgent === true;
            const message = {
                notification: {
                    title,
                    body,
                },
                data: {
                    type: payload.type,
                    titles: JSON.stringify(payload.titles),
                    bodies: JSON.stringify(payload.bodies),
                    language: userLanguage,
                    ...(payload.data ? { customData: JSON.stringify(payload.data) } : {}),
                },
                tokens,
                // High priority for urgent notifications — wakes device immediately
                ...(isUrgent ? {
                    android: { priority: 'high' as const },
                    apns: { headers: { 'apns-priority': '10' } },
                } : {}),
            };

            const response = await admin.messaging().sendEachForMulticast(message);

            // Handle failed tokens (remove invalid ones)
            if (response.failureCount > 0) {
                const failedTokens: string[] = [];
                response.responses.forEach((resp: { success: boolean }, idx: number) => {
                    if (!resp.success) {
                        failedTokens.push(tokens[idx]);
                    }
                });

                // Remove invalid tokens from database
                for (const token of failedTokens) {
                    await db
                        .delete(deviceTokens)
                        .where(eq(deviceTokens.token, token));
                }
            }
        } catch (error) {
            captureError(error, 'Failed to send push notification', { tags: { service: 'notifications' } });
            // Don't throw - push notification failure shouldn't break the main flow
        }
    }

    /**
     * Get notifications for a user.
     * Resolves the requested locale from the JSONB titles/bodies columns,
     * with English fallback if the locale isn't available.
     */
    async getNotifications(
        userId: string,
        limit: number = 20,
        offset: number = 0,
        lang: string = 'ar'
    ): Promise<{
        notifications: Array<{
            id: string;
            type: string;
            title: string;
            body: string;
            data: unknown;
            read: boolean;
            createdAt: Date | null;
        }>;
        unreadCount: number;
    }> {
        const notificationsList = await db
            .select({
                id: notifications.id,
                type: notifications.type,
                titles: notifications.titles,
                bodies: notifications.bodies,
                data: notifications.data,
                read: notifications.read,
                createdAt: notifications.createdAt,
            })
            .from(notifications)
            .where(eq(notifications.userId, userId))
            .orderBy(desc(notifications.createdAt))
            .limit(limit)
            .offset(offset);

        // Get unread count efficiently
        const [{ value: unreadCount }] = await db
            .select({ value: count() })
            .from(notifications)
            .where(and(
                eq(notifications.userId, userId),
                eq(notifications.read, false)
            ));

        return {
            notifications: notificationsList.map(n => {
                const titles = n.titles as Record<string, string>;
                const bodies = n.bodies as Record<string, string>;
                return {
                    id: n.id,
                    type: n.type,
                    title: titles[lang] || titles[FALLBACK_LANG] || '',
                    body: bodies[lang] || bodies[FALLBACK_LANG] || '',
                    data: n.data,
                    read: n.read ?? false,
                    createdAt: n.createdAt,
                };
            }),
            unreadCount,
        };
    }

    /**
     * Get unread notification count
     */
    async getUnreadCount(userId: string): Promise<number> {
        const [{ value }] = await db
            .select({ value: count() })
            .from(notifications)
            .where(and(
                eq(notifications.userId, userId),
                eq(notifications.read, false)
            ));

        return value;
    }

    /**
     * Mark a notification as read
     */
    async markAsRead(notificationId: string, userId: string): Promise<void> {
        await db
            .update(notifications)
            .set({ read: true })
            .where(and(
                eq(notifications.id, notificationId),
                eq(notifications.userId, userId)
            ));
    }

    /**
     * Mark all notifications as read for a user
     */
    async markAllAsRead(userId: string): Promise<void> {
        await db
            .update(notifications)
            .set({ read: true })
            .where(eq(notifications.userId, userId));
    }
}

export const notificationService = new NotificationService();
