import { db } from '../../db';
import { sql } from 'drizzle-orm';
import type { Logger } from '../../types/logger';
import { noopLogger } from '../../types/logger';
import { PROMPT_VERSION } from '@jawab24/shared';

/** Intent-aware cosine similarity thresholds for semantic cache hits.
 * Lower thresholds for formulaic intents (greetings), higher for nuanced ones (complaints). */
const INTENT_THRESHOLDS: Record<string, number> = {
    GREETING: 0.88,
    COMPLIMENT: 0.90,
    PRICE: 0.91,
    HOURS: 0.91,
    LOCATION: 0.91,
    BOOKING: 0.92,
    OFFERING_INFO: 0.92,
    PURCHASE_INTENT: 0.92,
    POLICY: 0.93,
    QUESTION: 0.93,
    BUSINESS_INQUIRY: 0.94,
    COMPLAINT: 0.95,
};
const DEFAULT_SIMILARITY_THRESHOLD = 0.93;

/** TTL backstop for semantic cache rows, aligned with the exact cache's 30-day
 * Redis TTL (ai.ts). Version scoping (kbActiveVersion + promptVersion) is the
 * real invalidation; this only bounds row age. The cleanup job
 * (utils/cleanup.ts) purges rows older than this — keep both in sync via this
 * constant or extended TTLs here are silently undone by cleanup. */
export const SEMANTIC_CACHE_TTL_DAYS = 30;

/** Intents where exact answers matter — skip semantic cache entirely.
 * Exact cache (hash-based) still applies; only vector similarity is bypassed. */
const SKIP_SEMANTIC_CACHE_INTENTS = new Set(['PRICE', 'PURCHASE_INTENT', 'COMPLAINT']);

export interface SemanticCacheHit {
    reply: string;
    intent: string;
    confidence?: string;
    flags?: string[];
}

/**
 * Metadata-scope filters for check(). An options object rather than trailing
 * positional optionals — `model` and `brandVoiceHash` are both
 * `string | undefined`, and a positional caller/callee mismatch on exactly
 * such a parameter is what silently disabled semantic reads for the default
 * fleet in #164.
 */
export interface SemanticCacheCheckOptions {
    channel?: string;
    replyStyle?: string;
    /**
     * Effective reply mode ('sales' | 'info'). Filtered STRICT both-ways like
     * brandVoiceHash, with 'sales' normalized to omitted — every legacy row was
     * generated by a sales prompt, so legacy rows serve sales requests and only
     * rows saved under 'info' serve info requests. Lenient matching would hand
     * a phone-asking sales reply to an info-mode page — the exact violation the
     * mode exists to prevent.
     */
    replyMode?: string;
    /** Resolved model when non-default; undefined means the default model. */
    model?: string;
    /** hashBrandVoice(notes) from ai.ts; undefined means no brand voice set. */
    brandVoiceHash?: string;
}

export interface SemanticCacheSaveParams {
    pageId: string;
    queryText: string;
    queryEmbedding: number[];
    intent: string;
    replyText: string;
    kbActiveVersion: number;
    channel?: string;
    replyStyle?: string;
    /**
     * Model the reply was generated with. Stored in metadata JSONB and filtered
     * application-side at check time so a workspace overridden to a non-default
     * model doesn't read replies generated by the default model (or vice versa).
     * Omit/undefined means the default model was used.
     */
    model?: string;
    /**
     * Short hash of the brand voice notes the reply was generated with
     * (hashBrandVoice in ai.ts). Stored in metadata and filtered app-side at
     * check time — brand voice is prompt-injected but settings saves never bump
     * kbActiveVersion, so without this scope a merchant who rewrites their
     * brand voice keeps reading old-voice replies until TTL expiry.
     * Omit/undefined means no brand voice was set.
     */
    brandVoiceHash?: string;
    /** Reply mode the reply was generated under — see SemanticCacheCheckOptions.replyMode. */
    replyMode?: string;
    metadata?: { confidence?: string; flags?: string[]; intent?: string };
}

/**
 * Semantic cache service — stores and retrieves AI replies
 * using vector similarity on query embeddings.
 *
 * Cache entries are scoped by:
 * - pageId (no cross-page leaks)
 * - intent (PRICE queries don't match HOURS queries even if words overlap)
 * - kbActiveVersion (stale entries auto-invalidate when KB is re-ingested)
 * - promptVersion (stale entries auto-invalidate when prompt is updated)
 * - channel + replyStyle + model + brandVoiceHash + replyMode (stored in
 *   metadata JSONB, filtered application-side)
 * - 30-day TTL backstop (SEMANTIC_CACHE_TTL_DAYS — version scoping above is the
 *   primary invalidation)
 */
export class SemanticCacheService {
    private logger: Logger = noopLogger;

    setLogger(logger: Logger): void {
        this.logger = logger;
    }

    /**
     * Check for a semantically similar cached reply.
     * Returns null on miss.
     */
    async check(
        pageId: string,
        queryEmbedding: number[],
        intent: string,
        kbActiveVersion: number,
        options: SemanticCacheCheckOptions = {},
    ): Promise<SemanticCacheHit | null> {
        const { channel, replyStyle, replyMode, model, brandVoiceHash } = options;
        // Skip semantic cache for price-sensitive intents — exact answers required
        if (SKIP_SEMANTIC_CACHE_INTENTS.has(intent)) {
            return null;
        }

        try {
            const vectorStr = `[${queryEmbedding.join(',')}]`;
            const threshold = INTENT_THRESHOLDS[intent] ?? DEFAULT_SIMILARITY_THRESHOLD;

            // Fetch top 5 candidates — application-level filtering by channel/replyStyle below
            const results = await db.execute(sql`
                SELECT
                    id,
                    reply_text,
                    intent,
                    metadata,
                    1 - (query_embedding <=> ${vectorStr}::vector) as similarity
                FROM semantic_cache
                WHERE page_id = ${pageId}
                  AND intent = ${intent}
                  AND kb_active_version_at_creation = ${kbActiveVersion}
                  AND prompt_version = ${PROMPT_VERSION}
                  AND created_at > NOW() - (${SEMANTIC_CACHE_TTL_DAYS} * INTERVAL '1 day')
                  AND 1 - (query_embedding <=> ${vectorStr}::vector) >= ${threshold}
                ORDER BY 1 - (query_embedding <=> ${vectorStr}::vector) DESC
                LIMIT 5
            `);

            const rows = results as unknown as Array<Record<string, unknown>>;
            if (rows.length === 0) {
                this.logger.debug('[SemanticCache] miss', { pageId, intent });
                return null;
            }

            // Application-level filter: match channel, replyStyle, and model from metadata.
            // Older rows pre-dating model scoping have meta.model === undefined; treat those
            // as "default model" so existing entries are still reusable for default-model
            // workspaces. An overridden workspace will never match those rows because its
            // `model` param is non-default.
            const matched = rows.find(row => {
                const meta = (row.metadata || {}) as Record<string, unknown>;
                if (channel && meta.channel && meta.channel !== channel) return false;
                if (replyStyle && meta.replyStyle && meta.replyStyle !== replyStyle) return false;
                const rowModel = (meta.model as string | undefined) ?? undefined;
                const wantModel = model || undefined;
                if (rowModel !== wantModel) return false;
                // Brand voice: strict both-ways match, unlike the model rule above.
                // Legacy rows (no brandVoiceHash field) can't tell us which voice
                // generated them, so they only serve workspaces with NO brand voice
                // set — a voice-having workspace must regenerate rather than risk
                // an old-voice reply.
                const rowBrandVoice = (meta.brandVoiceHash as string | undefined) ?? undefined;
                if (rowBrandVoice !== (brandVoiceHash || undefined)) return false;
                // Reply mode: strict both-ways with 'sales' normalized to omitted.
                // Legacy rows (no replyMode field) = sales rows, so they keep
                // serving sales requests; info requests only match rows saved
                // under 'info' (a sales reply may ask for the customer's phone —
                // never serve that to an info-mode page, or vice versa).
                const rowReplyMode = (meta.replyMode as string | undefined) ?? undefined;
                if (rowReplyMode !== (replyMode === 'info' ? 'info' : undefined)) return false;
                return true;
            });

            if (!matched) {
                this.logger.debug('[SemanticCache] miss (metadata scope mismatch: channel/style/model/brandVoice/replyMode)', { pageId, intent, channel, replyStyle, model, brandVoiceHash, replyMode });
                return null;
            }

            const row = matched;
            const similarity = Number(row.similarity);
            const meta = (row.metadata || {}) as { confidence?: string; flags?: string[]; intent?: string };

            this.logger.info('[SemanticCache] hit', {
                pageId, intent, similarity: similarity.toFixed(4),
            });

            // Update hit count asynchronously (fire-and-forget)
            this.incrementHitCount(row.id as string).catch(err => {
                this.logger.debug('[SemanticCache] hit count update failed', {
                    error: err instanceof Error ? err.message : String(err),
                });
            });

            return {
                reply: row.reply_text as string,
                // Prefer AI-classified intent (stored in metadata) over pre-GPT keyword intent
                intent: meta.intent || (row.intent as string),
                confidence: meta.confidence,
                flags: meta.flags,
            };
        } catch (error) {
            this.logger.error('[SemanticCache] check failed', {
                error: error instanceof Error ? error.message : String(error),
            });
            return null;
        }
    }

    /**
     * Save a new entry to the semantic cache.
     */
    async save(params: SemanticCacheSaveParams): Promise<void> {
        try {
            const vectorStr = `[${params.queryEmbedding.join(',')}]`;
            const metadata = {
                ...(params.metadata || {}),
                ...(params.channel ? { channel: params.channel } : {}),
                ...(params.replyStyle ? { replyStyle: params.replyStyle } : {}),
                ...(params.model ? { model: params.model } : {}),
                ...(params.brandVoiceHash ? { brandVoiceHash: params.brandVoiceHash } : {}),
                // 'sales' normalized to omitted so new sales rows stay byte-identical
                // to legacy rows (see the check-time filter).
                ...(params.replyMode === 'info' ? { replyMode: 'info' } : {}),
            };

            await db.execute(sql`
                INSERT INTO semantic_cache (
                    page_id, query_text, query_embedding, intent,
                    reply_text, metadata, kb_active_version_at_creation, prompt_version
                ) VALUES (
                    ${params.pageId},
                    ${params.queryText},
                    ${vectorStr}::vector,
                    ${params.intent},
                    ${params.replyText},
                    ${metadata}::jsonb,
                    ${params.kbActiveVersion},
                    ${PROMPT_VERSION}
                )
            `);

            this.logger.debug('[SemanticCache] saved', {
                pageId: params.pageId, intent: params.intent,
            });
        } catch (error) {
            this.logger.error('[SemanticCache] save failed', {
                error: error instanceof Error ? error.message : String(error),
            });
        }
    }

    /**
     * Invalidate all cache entries for a page (e.g., when KB changes).
     * Usually not needed because version-scoping handles this,
     * but useful for explicit cleanup.
     */
    async invalidateByPage(pageId: string): Promise<void> {
        await db.execute(sql`
            DELETE FROM semantic_cache WHERE page_id = ${pageId}
        `);
    }

    private async incrementHitCount(id: string): Promise<void> {
        await db.execute(sql`
            UPDATE semantic_cache
            SET hit_count = COALESCE(hit_count, 0) + 1
            WHERE id = ${id}::uuid
        `);
    }
}

export const semanticCacheService = new SemanticCacheService();
